spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: lyp82nlf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.wz: debug
  file:
    name: log/blog-dev.log
