spring:
  thymeleaf:
    mode: HTML

  profiles:
    active: dev

  freemarker:
    suffix: .ftl

  resources:
    static-locations: classpath:/static

  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp
